name: "🐞 Bug report"
description: "Create a report to help us reproduce and fix the bug"
labels: kind/bug
title: "[Bug] "

body:
  - type: textarea
    attributes:
      label: Command
      description: |
        Paste command used to create the bug
    validations:
      required: true

  - type: textarea
    attributes:
      label: Environment
      description: |
        Please run `python mmdet3d/utils/collect_env.py` to collect necessary environment information and copy-paste it here.
        You may add additional information that may be helpful for locating the problem, such as
          - How you installed PyTorch \[e.g., pip, conda, source\]
          - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)
    validations:
      required: true

  - type: textarea
    attributes:
      label: Reproduces the problem - error message
      description: |
        Please provide the error message or logs you got, with the full traceback.

      placeholder: |
        ```
        The error message or logs you got, with the full traceback.
        ```
    validations:
      required: true


